### ISSUE TITLE
Possible format change

### ISSUE THREAD

**Issue by Danizy** [Caier/ytfps#2]
Hello, i think yt has changed response again and the lib stopped working.

This can be fixed by changing the regex on `index.ts` line 30 to `/ytInitialData =.*?({[\s\S]*?});/`

Im not sure if this is is ideal solution but it works.

Cheers :)

**Comment by Caier** [comment]
Thanks for informing! Fixed in 6d3245ccd420e74ad6f9951881882b93bee085fe. You can update to v1.0.3!
