### ISSUE TITLE
Cannot read properties of undefined (reading 'playlistSidebarSecondaryInfoRenderer')

### ISSUE THREAD

**Issue by joshuajeschek** [Caier/ytfps#3]
Hi, I just tried to load the following playlist:
https://www.youtube.com/playlist?list=OLAK5uy_mPFpBY7OwJ9mFvKxWKzSDJUXNKY9YXjOA
And the following error occured:
```console
Error: Could not parse playlist metadata: Cannot read properties of undefined (reading 'playlistSidebarSecondaryInfoRenderer')
    at fetchFromPlaylist (...\node_modules\ytfps\out\index.js:70:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

What I noticed: The playlist does not seem to be like other playlists, maybe because it's some form of "album" playlist made by the artist themselves?

Anyways, some sort of insight would be great!

**Comment by joshuajeschek** [comment]
Okay, I'm currently investigating a bit, as it turns out, this playlist does not have two items in the `playlistSidebarRenderer.items` array.
I am currently looking at implementing a version where this is not needed, however some of the data may be undefined as a result in the end

**Comment by joshuajeschek** [comment]
Alright, I have a version that also accepts playlists like this. Would you be open to a PR?

**Comment by Caier** [comment]
Thanks for informing me about this issue, of course, you can open a PR if you want but if it's only a oneliner change you can send the fix in a reply here. I'll try to merge and test it asap.

**Comment by joshuajeschek** [comment]
Hey, I just opened a PR. It's nothing big, but I already had the test written and everything, so I just figured I'd open it anyways.

**Comment by Caier** [comment]
Hey, thanks again for committing, everything should work now. The v1.0.6 version should already be available on npm.

**Comment by joshuajeschek** [comment]
Nice!
